name: Gradle Publish

on:
  push:
    tags:
      - 'v*.*.*'
      
jobs:
  release:
    name: Release Version and publish packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Publish with gradle
      uses: gradle/gradle-build-action@v2.9.0
      with:
        arguments: publish
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: ./**/build/libs/*.jar
        generate_release_notes: true
      
